packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.2.2
  react: ^19.2.0
  react-dom: ^19.2.0
  rimraf: ^6.0.1
  tsc-alias: ^1.8.16
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
