packages:
  - docs
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
