packages:
  - docs
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  vite: ^7.1.10
  vite-tsconfig-paths: ^5.1.4

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
